# Generated by pointblank

library(pointblank)

tbl <- pointblank::game_revenue

test_that("column `player_id` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(player_id),
    threshold = 1
  )
})

test_that("column `session_id` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(session_id),
    threshold = 1
  )
})

test_that("column `item_type` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(item_type),
    threshold = 1
  )
})

test_that("column `item_name` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(item_name),
    threshold = 1
  )
})

test_that("column `item_revenue` is of type: numeric", {

  expect_col_is_numeric(
    tbl,
    columns = vars(item_revenue),
    threshold = 1
  )
})

test_that("values in `item_revenue` should be between `0.004` and `142.989`", {

  expect_col_vals_between(
    tbl,
    columns = vars(item_revenue),
    left = 0.004,
    right = 142.989,
    threshold = 0.1
  )
})

test_that("column `session_duration` is of type: numeric", {

  expect_col_is_numeric(
    tbl,
    columns = vars(session_duration),
    threshold = 1
  )
})

test_that("values in `session_duration` should be between `3.2` and `41`", {

  expect_col_vals_between(
    tbl,
    columns = vars(session_duration),
    left = 3.2,
    right = 41,
    threshold = 0.1
  )
})

test_that("column `acquisition` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(acquisition),
    threshold = 1
  )
})

test_that("column `country` is of type: character", {

  expect_col_is_character(
    tbl,
    columns = vars(country),
    threshold = 1
  )
})

test_that("values in `country` should be in the set of `Germany`, `Canada`, `South Korea` (and 20 more)", {

  expect_col_vals_in_set(
    tbl,
    columns = vars(country),
    set = c("Germany", "Canada", "South Korea", "Sweden", "Austria", "Hong Kong", "United States", "Mexico", "Egypt", "Denmark", "Norway", "Japan", "Australia", "South Africa", "Spain", "France", "Portugal", "Russia", "India", "Switzerland", "China", "Philippines", "United Kingdom"),
    threshold = 0.1
  )
})

test_that("entirely distinct rows across all columns", {

  expect_rows_distinct(tbl)
})

test_that("column schemas match", {

  expect_col_schema_match(
    tbl,
    schema = col_schema(
      player_id = "character",
      session_id = "character",
      session_start = c("POSIXct", "POSIXt"),
      time = c("POSIXct", "POSIXt"),
      item_type = "character",
      item_name = "character",
      item_revenue = "numeric",
      session_duration = "numeric",
      start_day = "Date",
      acquisition = "character",
      country = "character"
    ),
    threshold = 1
  )
})
